container:
  type: ColumnPanel
  properties: {col_widths: '{}'}
components:
- type: Image
  properties: {role: null, vertical_align: center, height: 200, tooltip: '', border: '',
    foreground: '', visible: true, display_mode: shrink_to_fit, spacing_above: none,
    source: '', spacing_below: none, background: '', horizontal_align: center}
  name: image_product
  layout_properties: {grid_position: 'ICSPNQ,XTBVAY'}
- type: Link
  properties: {role: null, url: '', align: center, tooltip: '', border: '', foreground: '#FF164E',
    visible: true, text: Delete, font_size: null, wrap_on: mobile, font: '', col_spacing: medium,
    spacing_above: none, icon_align: left, col_widths: '', spacing_below: none, italic: false,
    background: '', bold: false, underline: false, icon: 'fa:trash-o'}
  name: link_delete
  layout_properties: {grid_position: 'ASJQIA,KUOPZU'}
- type: Link
  properties: {role: null, url: '', align: center, tooltip: '', border: '', foreground: '',
    visible: true, text: Edit, font_size: null, wrap_on: mobile, font: '', col_spacing: medium,
    spacing_above: none, icon_align: left, col_widths: '', spacing_below: none, italic: false,
    background: '', bold: false, underline: false, icon: 'fa:pencil-square-o'}
  name: link_edit
  layout_properties: {grid_position: 'NNEYBL,OZWOQA'}
is_package: false
